### ISSUE TITLE
ejecución de nodos ROS2

### ISSUE THREAD

**Issue by ainchauspe** [erlerobot/ros2-install-ubuntu#1]
Parece que ROS2 se instala correctamente: no retorna ningún error al hacer el build.
Sin embargo al ejecutar un nodo mediante el binario:

```
./talker
```

Retorna el siguiente error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not create node: failed to create domain participant, at /home/anita/ros2_ws/src/ros2/rmw_opensplice/rmw_opensplice_cpp/src/functions.cpp:286
Aborted (core dumped)

```

**Comment by vmayoral** [comment]
Parece un `null pointer` en algún sitio. Si consigues reproducirlo, lo revisamos con GDB.

**Comment by ainchauspe** [comment]
Al ejecutar `./talker` sigue dando el mismo error de vez en cuando, no siempre:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not create node: failed to create domain participant, at /home/anita/test/src/ros2/rmw_opensplice/rmw_opensplice_cpp/src/functions.cpp:293
Aborted (core dumped)
```

**Comment by ainchauspe** [comment]
He ejecutado el build como siempre con `src/ament/ament_tools/scripts/ament.py build --build-tests --symlink-install` y le ha costado unos 11 minutos. A continuación, he utilizado `. install/local_setup.bash` y todo parece funcionar correctamente.
